### ISSUE TITLE
makefile for the SST driver fails

### ISSUE THREAD

**Issue by francistheodorecatte** [gregsidelinger/eqnx#1]
Running make build fails since gcc can't find sst.o (which hasn't been built yet?):

`/home/user/git/eqnx/drv/Makefile:178: ***`

`CC [M]  /home/user/git/eqnx/drv/sst.o`

`gcc: error: : No such file or directory`

`scripts/Makefile.build:257: recipe for target '/home/user/git/eqnx/drv/sst.o' failed`

`make[3]: *** [/home/user/git/eqnx/drv/sst.o] Error 1`

`make[3]: Target '__build' not remade because of errors.`

`Makefile:1353: recipe for target '_module_/home/user/git/eqnx/drv' failed`

`make[2]: *** [_module_/home/user/git/eqnx/drv] Error 2`

`make[2]: Target 'modules' not remade because of errors.`

`make[2]: Leaving directory '/usr/src/linux'`

`/home/user/git/eqnx/drv/makefile_2.6:38: recipe for target 'modules' failed`

`make[1]: *** [modules] Error 2`

`make[1]: Target 'build' not remade because of errors.`

`make[1]: Leaving directory '/home/user/git/eqnx/drv'`

`makefile:54: recipe for target 'build' failed`

`make: *** [build] Error 2`

Any idea what the heck is going on? Building on Debian Jessie with kernel 3.16.0-4-amd64.

Only made one modification to the Makefile. I added:
`MCFLAGS = "${CFLAGS}"`
And modified the original MCFLAGS line like so:
`MCFLAGS += ...`
So I could pass -Wno-error to keep the build from failing on warnings.

**Comment by gregsidelinger** [comment]
Not sure.  If I recall I did all of my testing on Fedora 17/18 which is pretty old.  I will see about spinning up Debian VM and seeing if it's a simple fix to support a newer build setup.  However I no longer have access to the hardware to test it so all I can do it make sure it compiles.

**Comment by francistheodorecatte** [comment]
I've got an Equinox SST-16P installed in the machine so I can test any changes you make pretty quickly.

Thanks for supporting this absolutely ancient device, by the way.

**Comment by francistheodorecatte** [comment]
Here's a copy of my slightly modified make file and a full error log:
[drv_makefile.txt](https://github.com/gregsidelinger/eqnx/files/848231/drv_makefile.txt)
[eqnx_build.txt](https://github.com/gregsidelinger/eqnx/files/848234/eqnx_build.txt)

**Comment by gregsidelinger** [comment]
What kernel version are you running?  And what packages did you install to get the correct headers in place?  It's been over a decade since I've used Debian for anything major and I'm not having any luck getting my build env setup correctly as the eqnx make file can not find the linux version.h file without me heavily modifying them which tells me I'm missing the correct deb.

**Comment by francistheodorecatte** [comment]
With a fresh a copy of Debian 8 Jessie x64, follow the following to get roughly my setup (this is all off the top of my head so I might get the commands wrong in places).

Update the system:
`sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade`

Get the linux kernel source and headers:
`sudo apt-get install linux-source linux-headers-$(uname -r)`

Untar the linux kernel source:
`sudo tar -xvf /usr/src/linux-source-* /usr/src`

Rename the new kernel source directory to /usr/src/linux for compatibility with the make file:
`sudo mv /usr/src/linux-source-* /usr/src/linux`

Prepare the kernel source for compiling:
`cd /usr/src/linux`

`sudo su`

`make oldconfig`

`make prepare`

`make scripts`

`exit`

That should get you in an environment with the sources and headers correctly configured for compiling kernel modules.

**Comment by gregsidelinger** [comment]
Check out the Linux-3.16 Branch and see if does cause any kernel panics.  I found two things that where causing it to fail.  One is no longer needed on newer kernels and the other,  while it compiles but no idea if it will work.  I would need to read up on the tty changes that went into 3.10.  tty_flip_buffer_push takes different input now.

**Comment by francistheodorecatte** [comment]
I'll give you an update tomorrow once I have access to the machine with the SST card in it.

**Comment by francistheodorecatte** [comment]
Okay changed to the Linux-3.16 branch, and this is what I get:
[eqnx_build_new.txt](https://github.com/gregsidelinger/eqnx/files/854927/eqnx_build_new.txt)

**Comment by gregsidelinger** [comment]
Try to use the first commit to the branch.  My second commit was suppose to do proper if statements based on the kernel version and it must not be working.

**Comment by francistheodorecatte** [comment]
Checked out to commit c3248ef... and ran make; here's the new build log:
[eqnx_build_new2.txt](https://github.com/gregsidelinger/eqnx/files/855334/eqnx_build_new2.txt)

It's failing at an include for curses.h now?

**Comment by gregsidelinger** [comment]
install ncurse-dev

**Comment by francistheodorecatte** [comment]
The kernel module built!

I ran
`sudo insmod ./drv/eqnx.ko`

And checked it loaded with
`sudo tail -f /var/log/messages`

> Mar 20 09:28:54 felony kernel: [351880.381584] init_module()
> Mar 20 09:28:54 felony kernel: [351880.381588] Loading Equinox SuperSerial Technology Device Driver Version 4.12e
> Mar 20 09:28:54 felony kernel: [351880.381589] Copyright (c) 1989-2007 Equinox Systems Inc. All Rights Reserved.
> Mar 20 09:28:54 felony kernel: [351880.387351] EQNX SST Board 0 : id 80c8 (SST-16P No panel)
> Mar 20 09:28:54 felony kernel: [351880.407201] EQNX: Driver Enabled for 1 board(s).

Then I ran 
`sudo ./utils/ssmkn`

and
`sudo ./utils/sstty -c`

> user@felony:\~/git/eqnx/utils$ sudo ./sstty -c
> Board 1 id 0xc8 SST-16P No panel Slot 0
> user@felony:\~/git/eqnx/utils$ ls /dev

![ttyq](https://cloud.githubusercontent.com/assets/14878852/24113389/05b32428-0d73-11e7-8c7a-d077f9dcf6ce.PNG)

Looks like it works! I can't plug a bunch of serial devices (TVs in my case) into it right now to test, but I think getting this far is enough to close this issue.

Thanks again for helping me out.
