### ISSUE TITLE
have a compile with newer kernel - 4.15.18+

### ISSUE THREAD

**Issue by donharter** [gregsidelinger/eqnx#3]
I have made some changes to master branch.  I can get it to compile with kernel 4.15.18+.
If I get permission I will upload my branch.

**Comment by gregsidelinger** [comment]
Send a pull request if able.

**Comment by donharter** [comment]
I got your email but the return address was rejected by thunderbird.  I tried sending you a tar archive of the changes that I made.

**Comment by gregsidelinger** [comment]
Are you able to fork the code and send a pull request?  Or maybe you can attach the tar fine in the comment here.

**Comment by donharter** [comment]
I could fork your code to a personal "archive".  I still can't send you email requests.
The return address generated by github is invalid.
Here is where it is forked to:  https://github.com/donharter/eqnx/branches
make sure you read the notes/wiki.

**Comment by gregsidelinger** [comment]
I created a pull request and merged your changes into my stuff.  I will do some testing and tag a new release later this week.
