### ISSUE TITLE
Can't build kernel module for CentOS6 with stock kernel

### ISSUE THREAD

**Issue by amorting** [gregsidelinger/eqnx#6]
Hello !

Can you help build this driver for CentOS6 last stock kernel ?

[root@stat-vas eqnx-master]# make
cd drv; make build
make[1]: Entering directory `/root/Workspace/eqnx-master/drv'
make  -C /usr/src/linux-2.6.32-754.17.1.el6.i686 SUBDIRS=/root/Workspace/eqnx-master/drv modules
make[2]: Entering directory `/usr/src/kernels/2.6.32-754.17.1.el6.i686'
  CC [M]  /root/Workspace/eqnx-master/drv/sst.o
/root/Workspace/eqnx-master/drv/sst.c:113:32: error: linux/sched/signal.h: No such file or directory
/root/Workspace/eqnx-master/drv/sst.c:8590: error: conflicting types for ‘tty_prepare_flip_string_flags’
include/linux/tty_flip.h:8: note: previous declaration of ‘tty_prepare_flip_string_flags’ was here
/root/Workspace/eqnx-master/drv/sst.c: In function ‘tty_prepare_flip_string_flags’:
/root/Workspace/eqnx-master/drv/sst.c:8593: warning: passing argument 1 of ‘tty_buffer_request_room’ from incompatible pointer type
include/linux/tty_flip.h:4: note: expected ‘struct tty_struct *’ but argument is of type ‘struct tty_port *’
/root/Workspace/eqnx-master/drv/sst.c:8595: error: ‘struct tty_port’ has no member named ‘buf’
/root/Workspace/eqnx-master/drv/sst.c:8596: warning: implicit declaration of function ‘char_buf_ptr’
/root/Workspace/eqnx-master/drv/sst.c:8596: warning: assignment makes pointer from integer without a cast
/root/Workspace/eqnx-master/drv/sst.c:8597: warning: implicit declaration of function ‘flag_buf_ptr’
/root/Workspace/eqnx-master/drv/sst.c:8597: warning: assignment makes pointer from integer without a cast
/root/Workspace/eqnx-master/drv/sst.c: In function ‘megainput’:
/root/Workspace/eqnx-master/drv/sst.c:8700: warning: passing argument 1 of ‘tty_prepare_flip_string_flags’ from incompatible pointer type
/root/Workspace/eqnx-master/drv/sst.c:8590: note: expected ‘struct tty_port *’ but argument is of type ‘struct tty_struct *’
At top level:
cc1: warning: unrecognized command line option "-Wno-incompatible-pointer-types"
make[3]: *** [/root/Workspace/eqnx-master/drv/sst.o] Error 1
make[2]: *** [_module_/root/Workspace/eqnx-master/drv] Error 2
make[2]: Leaving directory `/usr/src/kernels/2.6.32-754.17.1.el6.i686'
make[1]: *** [modules] Error 2
make[1]: Leaving directory `/root/Workspace/eqnx-master/drv'
make: *** [build] Error 2

**Comment by gregsidelinger** [comment]
I finally merged #4 from @donharter which looks to address this issue.  The module builds on CentOS6 now but I can not confirm it works as I no loner have access to the hardware.  Let me know if this works.

**Comment by amorting** [comment]
> I finally merged #4 from @donharter which looks to address this issue. The module builds on CentOS6 now but I can not confirm it works as I no loner have access to the hardware. Let me know if this works.

Bingo ! :) Thank you!

**Comment by amorting** [comment]
:)
